version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tickets-please-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - tickets-please-network
    depends_on:
      - db
      # - redis

  nginx:
    image: nginx:alpine
    container_name: tickets-please-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - tickets-please-network
    depends_on:
      - app

  db:
    image: mysql:latest
    container_name: tickets-please-mysql
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_ROOT_PASSWORD: root
    ports:
     - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - tickets-please-network

  # redis:
  #   image: redis:alpine
  #   container_name: tickets-please-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./docker/redis:/data
  #   networks:
  #     - tickets-please-network

  node:
    image: node:20
    container_name: tickets-please-node
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - tickets-please-network

networks:
  tickets-please-network:
    driver: bridge 